services:
    dev:
        image: webdevops/php-dev:8.3
        volumes:
            - .:/avro-php
            - ${DOCKER_HOME:-$HOME}:${DOCKER_HOME:-$HOME}
            - /etc/passwd:/etc/passwd
            - /etc/group:/etc/group
        environment:
            HOME: ${DOCKER_HOME:-$HOME}
            PHP_IDE_CONFIG: serverName=avro-php
        working_dir: /avro-php
        user: root
        command: runuser -u ${DOCKER_USER:-$USER} -- bash

    test-generator:
        image: node:latest
        volumes:
            - .:/avro-php
            - ${DOCKER_HOME:-$HOME}:${DOCKER_HOME:-$HOME}
            - /etc/passwd:/etc/passwd
            - /etc/group:/etc/group
        environment:
            HOME: ${DOCKER_HOME:-$HOME}
            npm_config_cache: /tmp/.npm
        working_dir: /avro-php
        command: runuser -u ${DOCKER_USER:-$USER} -- bash -c "cd tests/Integration/TestCaseGenerator && npm ci && node ."