services:
    dev:
        image: webdevops/php-dev:8.3
        volumes:
            - .:/avro-php
            - $HOME:$HOME
            - /etc/passwd:/etc/passwd
            - /etc/group:/etc/group
        environment:
            - HOME
            - PHP_IDE_CONFIG=serverName=avro-php
        working_dir: /avro-php
        user: root
        command: runuser -u $USER -- bash