name: Test

on: [push]

jobs:
    docker:
        timeout-minutes: 10
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Build docker image
              run: USER_ID=$(stat -c %u .) GROUP_ID=$(stat -c %g .) ./docker-dev build dev

            - name: Install dependencies
              run: ./docker-dev run --rm dev composer install

            - name: Run phpunit
              run: ./docker-dev run --rm dev vendor/bin/phpunit --testdox

            - name: Run phpstan
              run: ./docker-dev run --rm dev vendor/bin/phpstan --memory-limit=512M

            - name: Run ecs
              run: ./docker-dev run --rm dev vendor/bin/ecs